image: gitpod/workspace-full

tasks:
  - name: Start Stack-TR-InvenTree
    init: |
      sudo apt-get update && sudo apt-get install -y docker.io docker-compose
      sudo usermod -aG docker gitpod
      docker --version
      docker-compose --version
      docker-compose pull
    command: |
      echo "🚀 Starting Stack-TR-InvenTree..."
      docker-compose up

ports:
  - port: 8000
    onOpen: open-preview
